apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: acrboombasticdev01.azurecr.io/sample/hello-world:v1
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
