apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-virtual-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-virtual-node
  template:
    metadata:
      labels:
        app: nginx-test-virtual-node
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: 100m
      tolerations:
        - key: "virtual-kubelet.io/provider"
          operator: "Equal"
          value: "azure"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
