allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: azurefile-csi-pep
mountOptions:
- mfsymlinks
- actimeo=30
- nosharesock
parameters:
  storageAccount: staks123321dev01
  resourceGroup: rg-aks-dev-01
  skuName: Standard_LRS
  networkEndpointType: privateEndpoint
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate