trigger:
  branches:
    include:
      - main
  paths:
    include:
      - runbooks

# schedules:
#   - cron: 0 0 * * *
#     branches:
#       include:
#         - main
#     always: true

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: sub-xxx-labb-01
  environment: prod
  workingDirectory: runbooks

steps:
  - task: AzureCLI@2
    displayName: Set environment variables
    inputs:
      azureSubscription: ${{ variables.azureSubscription }}
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
        echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
  - script: |
      terraform init -input=false
      terraform plan -out=tfplan -input=false
      terraform apply --auto-approve -input=false
    displayName: "Terraform"
    workingDirectory: runbooks
